name: Deploy Jekyll site to Pages

on:
  push:
    branches: 
      - main  # Adjust branch name as per your default branch
  workflow_dispatch:

permissions:
  contents: write  # Ensure contents permission is set to write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to the latest version
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify your desired Ruby version
          bundler-cache: true
      - name: Install Jekyll and dependencies
        run: |
          gem install bundler jekyll
          bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build --baseurl "/website.github.io"
        env:
          JEKYLL_ENV: production
      - name: Archive artifacts
        uses: actions/upload-artifact@v4  # Updated to the latest version
        with:
          name: jekyll-site
          path: _site  # Path to your Jekyll build output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3  # Updated to the latest version
        with:
          name: jekyll-site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages  # Set your target branch for deployment
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
