name: Node.js and Jekyll CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 20.x]  # Updated to include Node.js 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build JavaScript assets
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify your desired Ruby version
          bundler-cache: true

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --baseurl "/website.github.io"
        env:
          JEKYLL_ENV: production

      - name: Archive Jekyll artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jekyll-site
          path: _site  # Path to your Jekyll build output directory

  deploy-to-pages:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Download Jekyll artifacts
        uses: actions/download-artifact@v2
        with:
          name: jekyll-site
          path: _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: true  # Ensure Jekyll processing on GitHub Pages
          disable_nojekyll: false
          exclude_assets: .github
